version: "3.7"
services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: acid
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_USERNAME: acid
      DB_PASSWORD: password
      DB_DATABASE: develop
      DEPLOY_ENV: dev
    working_dir: /home/node/
    volumes:
      - "./src:/home/node/src"
      - "./test:/home/node/test"
    ports:
      - "8080:8080"
    networks:
      - default
