FROM node:18-alpine

RUN apk add build-base git

WORKDIR /home/node
ADD ./package.json ./package.json
ADD ./yarn.lock ./yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 8080

CMD yarn start:dev
